version: '3.5'

services:
  sgamongodb:
    container_name: sga_mongodb
    # image: mongodb
    image: mongodb-raspberrypi4-unofficial-r7.0.4

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${COMPOSE_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${COMPOSE_MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${COMPOSE_MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    #volumes: -dbdata6:/data/db
    networks:
      - sga-network
    env_file:
      - .env.development.local

  sgaapi:
    container_name: sga-mpr
    build:
      context: .
      args:
        - no_cache='true'
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${COMPOSE_MONGODB_URI}
    ports:
      - '3003:3003'
    depends_on:
      - sgamongodb
    #volumes:
    #  - .:/src
    networks:
      - sga-network
    env_file:
      - .env.development.local

#volumes:
#  dbdata6:


networks:
  sga-network:
    driver: bridge
