FROM node:18

# RUN apt-get update && apt-get install -y git

# RUN git clone https://github.com/LuisCepeda/sga_mpr /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3003

CMD [ "npm","run","start:prod" ]